environment:
 name: dev
application:
 name: "Mule Template API"
api:
 name: "mule-template-api-${environment.name}"
 id: "154975"
 version: "v1"
 http:
  listener:
   path: "/api/${api.name}/${api.version}/*"
   host: "0.0.0.0"
   port: "8081"
   